# environment.yml
name: wildlife-scanner
channels:
  - conda-forge
dependencies:
  - python=3.8
  - gitpython
  - numpy
  - pandas
  - matplotlib
  - Pillow
  - tqdm
  - scikit-learn
  - pytorch
  - torchvision
  - tensorflow
  - pyyaml
  - omegaconf
  - black